name: 'Airtable Worklog'
description: '오픈튜토리얼스 업무일지용 github action'
inputs:
  AIRTABLE_SECRET:  # id of input
    description: 'Airtable API key'
    required: true
    default: ''
  AIRTABLE_BASE:
    description: 'Airtable base id'
    required: true
    default: ''
outputs:
  result: # id of output
    description: '실행결과 및 로그'
runs:
  using: 'node12'
  main: 'index.js'
 