on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: opentutorials-org/action-airtable-worklog@v1.0.6
      with:
        AIRTABLE_SECRET: ${{ secrets.AIRTABLE_SECRET }}
        AIRTABLE_BASE: ${{ secrets.AIRTABLE_BASE }}
     